### ISSUE TITLE
Molecular type attribute

### ISSUE THREAD

**Issue by ahwagner** [ga4gh/vrs#179]
Sequences are currently untyped, but may benefit from DNA/RNA/AA designation. This was an early design decision I think we should revisit. Starting this thread as a place to collect use cases and issues for making such a change.

**Comment by rrfreimuth** [comment]
+1 to the idea, but details are TBD.

Is the intent for this to restrict the alphabet used to represent the sequence?  Or is it to facilitate consumption or processing of the sequence?  I suspect the latter, but we need to clarify this.

My initial thoughts are a single attribute to capture type, bound to an ontology that allows the author to subtype as needed (e.g., mRNA vs. RNA).  That approach provides flexibility but may complicate digests as a result.  An alternative is to bind a simple value set containing the main molecular types (DNA, RNA, protein).

**Comment by ahwagner** [comment]
To be considered for v2
