### ISSUE TITLE
Implement Location class to store symbolic genes and gene regions

### ISSUE THREAD

**Issue by reece** [ga4gh/vrs#201]
Split GeneLocation proposal from #181 into separate feature.

**Comment by reece** [comment]
Use case: Provide a symbolic reference to a gene to be used as (with the role of) a Location. For example, "PTEN deletion".

Consideration should also be given to converting symbolic gene locations onto sequence coordinates, how this might happen, and whether such a transformation is required. (Without this, queries like "identify variation within a gene" would be impossible.

**Comment by reece** [comment]
**Naming Consideration**
Current Location subclasses are locations within that coordinate system. For example, SequenceLocation is a location *on* a Sequence (as coordinate system), not the location *of* a sequence.

We have been calling the proposed class a "GeneLocation". Under the current naming pattern, this would imply locations *on*
Gene. However, it's much more challenging to contemplate the addressable components of a gene.

**Comment by sarahhunt** [comment]
These seem more like definitions of sets of variants, rather than locations. 
We have a similar thing in DDG2P where we seek HMX1,1 "loss of function", variants
