### ISSUE TITLE
Consider using term "sequence state" in lieu of "sequence expression"

### ISSUE THREAD

**Issue by larrybabb** [ga4gh/vrs#234]
https://github.com/ga4gh/vr-spec/blob/4c433a6ce0ed09e2e47f3aa8ac05d1f9a771cd3f/notebooks/develop.ipynb#L154

It seems that this "new" abstract concept will be focused on a number of derivative forms that are based on the notion of a "sequence of residues". As such the term "expression" seems a bit presumptuous since the first two forms are a literal string (which could be construed as an expression I suppose) and a sequence location which does not seem to fit the definition of an "expression".  If we were to name this based on what it is we require this class to project then one might argue that we are trying to project a variety of "states" that can be produced or derived from "expressions", "literals", "constructs", etc... all founded on the consistent principles behind a string of residues (aka sequence).

If state causes too much conflation with the attribute of "state" already used in the Allele concept then we may want to change the name (or consider whether these are one and the same)?

**Comment by reece** [comment]
We already have a SequenceState. However, I agree that merging these is logical and simplifying.

**Comment by reece** [comment]
We've got several directions on this topic, but the last I remember is that we're going to use SequenceExpression, but conceptually merge with SequenceState. Since that's done, I'm closing. Reopen if needed.
