### ISSUE TITLE
Exact and Inexact derived sequences from sequence location

### ISSUE THREAD

**Issue by larrybabb** [ga4gh/vrs#235]
https://github.com/ga4gh/vr-spec/blob/4c433a6ce0ed09e2e47f3aa8ac05d1f9a771cd3f/notebooks/develop.ipynb#L163

I think we will need both exact and inexact sequence expressions/states from sequence locations in v1.2.  One might argue that the "inexact" form is more prevalent than the "exact" form.  

I think the need for "inexact" sequence state from sequence location is evident from the may large Dupes in ClinVar (Search "duplication"[Type of variation] Sort by: Position Filters: Between 50 and 500 kb).  

Whether we consider all of these inexact nested interval dupes as tandem (repeating) sequences or abundance (no known location) we will still need the idea of the "region" of the sequence represented by the "inexact" sequence state from a given sequence location.

Here are some interesting examples of dupes varying sizes that are characterized as likely tandem vs uncertain tandem-ness.

> * [NC_000010.10:g.(?_72179670)_(72360658_?)dup](https://www.ncbi.nlm.nih.gov/clinvar/variation/583472/)   (Invitae: As the precise location of this duplication is unknown, it may be in tandem or it may be located elsewhere in the genome.)
> * [NC_000009.11:g.(?_113457663)_(113524508_?)dup](https://www.ncbi.nlm.nih.gov/clinvar/variation/583532/)  (Invitae: This variant results in a copy number gain of the genomic region encompassing exons 4-8 of the MUSK gene. While the exact position of this variant cannot be determined from this data, sub-genic copy number gains are generally in tandem (PMID: 25640679) and may result in an absent or disrupted protein product.)

**Comment by andreasprlic** [comment]
Thanks! I think your comment actually contains two (separate?) aspects of imprecision 1) Lack of knowledge of the exact breakpoint of a CNV call, but confidence that a specific sub-region is impacted.  2) Unclear if a duplication is a tandem duplication vs translocation. In some cases this can be known, in others it might be unclear.
