### ISSUE TITLE
Add '?' or 'null' as a valid unbounded start or end value in SimpleInterval

### ISSUE THREAD

**Issue by larrybabb** [ga4gh/vrs#236]
https://github.com/ga4gh/vr-spec/blob/4c433a6ce0ed09e2e47f3aa8ac05d1f9a771cd3f/notebooks/develop.ipynb#L55

The notion of unbounded endpoints on intervals is necessary for NestedIntervals so this should be made explicit how this is done here (I think).

This is based on the assumption that we will be supporting intervals with open bounds on either end.

While it is true that most (if not all) examples I've seen the notion of unbounded endpoints would be applied in our NestedInterval and would always be "balanced" either both inner or both outer are unbounded.

If anyone could provide a use case of "unbalanced" intervals that apply to real world examples that would be helpful.

**Comment by reece** [comment]
The [Implementation Guidance bullet #2](https://vrs.ga4gh.org/en/develop/terms_and_model.html#nestedinterval) already covers null. Please check language and reopen issue and/or submit a PR if you believe this needs further clarification.
