### ISSUE TITLE
Is "Gene" an identifiable object in VRS?

### ISSUE THREAD

**Issue by larrybabb** [ga4gh/vrs#237]
https://github.com/ga4gh/vr-spec/blob/4c433a6ce0ed09e2e47f3aa8ac05d1f9a771cd3f/notebooks/develop.ipynb#L120

Since Gene is not a Variation, Location or Sequence, we should clarify if this is inside the VRS scope and if so, does it descend from some superclass concept that may spawn other child concepts useful to VRS?

Also, is Gene going to be able to produce a VRS computed identifier? If so, then we should provide the rules for how the digest is created for this class of object.  If not, then are we simply providing the ability to have VRS depend on specific externally managed concepts without any special abilities to "wrap" it in a VRS object?

**Comment by reece** [comment]
The intention is for Gene to *not* be identifiable. Like AlleleState, it is purely for data structure. It is a standalone type.

I do not see a use case for creating a VRS id for an object that is defined elsewhere.

**Comment by reece** [comment]
Confirming that we subsequently decided that Gene is not identifiable for 1.2. Closing.
