### ISSUE TITLE
Can RepeatStates be nested?

### ISSUE THREAD

**Issue by larrybabb** [ga4gh/vrs#238]
https://github.com/ga4gh/vr-spec/blob/4c433a6ce0ed09e2e47f3aa8ac05d1f9a771cd3f/notebooks/develop.ipynb#L244

There was some discussion of being about to nest repeatState so that a given repeating pattern could in itself be used in a higher order repeating pattern. While it is unclear whether there is real use cases for this, it does seem like the entire notion of the 'sequence' attribute within the RepeatState really represents the notion of a sequence state (or expression).  If this is a reasonable argument then one could consider then whether a RepeatState itself is a type of SequenceState/Expression.

Whether we decide to limit RepeatState to only encapsulate Sequence Expressions (or States) that are fundamentally atomic concepts. We should be clear to clarify that this is a molecular "sequence-based interval" or "chromosomal-based band" linear repeating outcome. And it could be compared to the notion of a reference repeat state of the same type in order to determine what the actual variant from reference is (when desired).

**Comment by reece** [comment]
Yes. SequenceExpressions are nestable. A repeat of a repeat is possible. Closing.
