### ISSUE TITLE
Reconsider cytoband ordering

### ISSUE THREAD

**Issue by reece** [ga4gh/vrs#240]
Suggested by @ahwagner 

Change to mimic sequence location, order as p descending .. q ascending .

**Comment by ahwagner** [comment]
This is a departure from ISCN nomenclature and the [Mitelman database](https://mitelmandatabase.isb-cgc.org/case_details?refno=4022&caseno=11) (which strictly uses ISCN). In those cases, short-form representation of regions from multiple bands use a notation such as p12p23, along with textual elements indicating the type of process (inv, dup, del, etc.). Some evaluated resources (e.g. [NCBI Gene](https://www.ncbi.nlm.nih.gov/gene/192644) and the [Atlas of Cytogenetics](http://atlasgeneticsoncology.org/Indexbychrom/idxa_2.html)) describe regions using a cytoband range syntax, e.g. p23-p12, keeping a pter->cen->qter orientation when describing start to end ranges.

As nucleotide sequence assemblies follow a pter->cen->qter orientation for coordinates, I propose we mirror this in our cytoband sequence coordinate guidance to better align between the VRS Location systems.

**Comment by reece** [comment]
@ahwagner: You have been closer to this. Would you please take a stab at the text under Implementation Guidance?

**Comment by reece** [comment]
Scratch that... I just submitted #245 to make this easier. Please approve/improve there.

**Comment by ahwagner** [comment]
Addressed in #245.
