### ISSUE TITLE
Add an FAQ appendix to the spec...

### ISSUE THREAD

**Issue by larrybabb** [ga4gh/vrs#242]
There are likely enough small common questions that have been raised that should be made public so that the community is aware that we have a position about certain considerations even if it is "to be addressed later".

As an example...
How does VRS handle DNA variants based on sequences on the reverse strand?
Do both the forward and reverse strands get digested for a given DNA molecule?
Are all DNA sequences based on the forward "reference" strand?

Maybe we can use this issue to capture other FAQs and then compile a list to determine which ones warrant publication in the spec as an Appendix?

**Comment by reece** [comment]
I started a [242-add-faq branch](https://github.com/ga4gh/vrs/tree/242-add-faq).

@larrybabb Want to take a stab at compiling and answering more questions?
