### ISSUE TITLE
Ensure that all classes are documented

### ISSUE THREAD

**Issue by reece** [ga4gh/vrs#246]
Ensure that all classes have rst documentation. The following list is generated from vrs.yaml:

- [x] AbsoluteAbundance #46 
- [ ] Allele #260
- [ ] ~BaseOffset~ **Not present in vrs.yaml**
- [x] ChromosomeLocation
- [x] CURIE
- [ ] Cytoband #262
- [x] CytobandInterval 
- [ ] ~DateTime **Is this needed?** Reece: No. Removing.
- [x] DerivedSequence
- [ ] Gene (Yes, but discussion needed)
- [x] Haplotype
- [x] IntegerRange
- [x] LiteralSequence
- [x] Location
- [x] MolecularVariation
- [x] NestedInterval
- [x] OtherVariation
- [x] RelativeAbundance #46 
- [x] RepeatedSequence
- [x] SequenceExpression
- [x] SequenceInterval
- [x] SequenceLocation
- [x] SequenceState (moved to Deprecated Classes)
- [x] SimpleInterval
- [x] SystemicVariation
- [x] Text
- [x] Variation
- [x] VariationSet

**Comment by ahwagner** [comment]
Updating above with class-specific issues as needed.

Related issues:
- [ ] #259 Update schema diagram

**Comment by reece** [comment]
I updated the table above based on work #265 that is not yet in develop.
