### ISSUE TITLE
Remove develop branch

### ISSUE THREAD

**Issue by ahwagner** [ga4gh/vrs#251]
We are going to rename our `develop` branch to `main` to follow current GitHub conventions describing the primary development branch.

**Comment by reece** [comment]
Update: We actually already had a main branch. I updated it to be even with the last release.

So, for 1.2, we'll merge all of our changes into `develop`, which will effectively be the 1.2 dev branch. We'll then create a PR of `develop` → `main` to get comments. When approved, we'll merge and delete `develop`.

**Comment by reece** [comment]
Since deleting this branch will happen as a consequence of the PR, there's no work to do. I propose that we close this issue.

@ahwagner , please close if you agree.
