### ISSUE TITLE
Add VRS citation to rst_epilog

### ISSUE THREAD

**Issue by ahwagner** [ga4gh/vrs#261]
VRS is cited on the intro page, and in places where we use content from the manuscript. It will probably be added to the FAQ page #242 also.

Therefore, a shorthand way of referencing it that allows us to update the format as the publication advances would be helpful.

Add the citation block to `rst_epilog`.

**Comment by reece** [comment]
Probably also worth standardizing citation formats throughout.
Thanks for dealing with this.
