### ISSUE TITLE
Support circular sequences

### ISSUE THREAD

**Issue by rrfreimuth** [ga4gh/vrs#274]
During the VRS call on Feb 8, 2021, the limitations of the current model were discussed with regard to support for circular sequences (e.g., mitochondrial chromosome).  The decision was made to add an issue to motivate a potential extension to support this capability, potentially for the 1.3 release.  This issue serves as a placeholder for discussion related to that potential extension.

**Comment by ahwagner** [comment]
Addressed in #485
