### ISSUE TITLE
Define how to refer to reverse complement sequences

### ISSUE THREAD

**Issue by reece** [ga4gh/vrs#276]
Use cases:

* Insert inverted sequence
* Feature (gene, exon, intron, transcript) defined on rev comp

**Comment by ahwagner** [comment]
This is now an issue of generalizability of the `reverse_complement` feature of the `DerivedSequenceExpression` ([schema](https://github.com/ga4gh/vrs/blob/1.2/schema/vrs.yaml#L458-L459)). Putting it on the v2-dev discussion list.

**Comment by ahwagner** [comment]
the current SV draft uses seqloc `start` and `end` inside `Adjacency` structures to convey sequence directionality.
