### ISSUE TITLE
Consider IUPAC Ambiguity Codes and amino acid ambiguity

### ISSUE THREAD

**Issue by ahwagner** [ga4gh/vrs#278]
Currently we allow all IUPAC ambiguity codes for VRS, but no parallel mechanism for amino acids.

Section 1.4.1 of v4.2 of the VCF specification under Ref and Alt, only A, C, G, T, and N (or * for alt if missing due to upstream deletion).

I think we should recommend against using IUPAC ambiguity, but continue to support for older implementations using those codes. We should also provide a mechanism for expressing multiple possible alternate states for _any_ variation.

@larrybabb

**Comment by reece** [comment]
Recommend where? Throughout VRS?

Strictly speaking, disallowing ambiguity codes would mean not being able to use GRCh references (which use ambiguity codes), so a global recommendation against them would be problematic.

What real problem does this proposal try to solve?

**Comment by ahwagner** [comment]
Yes, understood re:GRCh*. We would still need to allow ambiguity codes here and wherever else they are used, but recommend against doing so for variation, specifically. 

The real problem to solve is when we have a case like this:
[V600 Mutations in the Combi-v trial](https://civicdb.org/events/genes/5/summary/variants/17/summary/evidence/1411/summary#evidence)

To represent this, we will need a new, unspecified mechanism to be able to represent the set of amino acid changes on a protein sequence represented by the BRAF V600 string (e.g. an AlternateSequencesExpression).

We can _already_ represent a set of nucleotide change at a location (e.g. multiple alleles of a dbSNP rsID), through the use of ambiguity codes. In this hypothetical situation, depending on the type of sequence, the mechanism by which you express ambiguity would be different. This is problematic, as VRS treats all sequences as identical concepts (no distinction between DNA, RNA, AA; a sequence of 1 adenine == a sequence of 1 alanine). Alternatively, we create a new mechanism and you can use it for DNA/RNA/AA, but then there exists 2 ways of representing the _same_ concept for DNA or RNA.
