### ISSUE TITLE
Use generalized ranges for locations and counts

### ISSUE THREAD

**Issue by reece** [ga4gh/vrs#285]
**Note: This issue was originally the 1.2 punchlist. That punch list is now represented as [issues for the 1.2 milestone](https://github.com/ga4gh/vrs/milestone/5).**

Consider whether and how to implement generalized ranges for locations and copy counts.

Rational: 
* NestedInterval does not follow a typical interval structure (i.e., it is a tuple of <inner,outer> rather than <start, end> as used elsewhere in VRS
* There is interest in considering a generalized range type for sequence locations and copy counts. 

Also, consider what to borrow from [FHIR Data Types](https://www.hl7.org/fhir/datatypes.html).

**Comment by ahwagner** [comment]
Added a couple of bullets above to resolve https://github.com/ga4gh/vrs/pull/286#pullrequestreview-645017577 discussion and comments from @pnrobinson and @julesjacobsen on the necessity of nested RepeatedSequenceExpression messages.

**Comment by ahwagner** [comment]
- [ ] Replace NestedInterval with new range structures (specifics TBD)
- [ ] Clarify use of None/null
- [ ] Use additionalProperties uniformly
- [ ] Use required attributes uniformly
- [ ] Evaluate CopyNumber subjects (Location vs SequenceExpression)
- [ ] Revisit RepeatedSequenceExpression as subject of RepeatedSequenceExpression
