### ISSUE TITLE
Consider adding `_id` to `Gene`

### ISSUE THREAD

**Issue by ahwagner** [ga4gh/vrs#298]
While a computed identifier for `Gene` probably isn't useful, it is helpful to have an `_id` slot so this concept can be referenced directly by a CURIE instead of an in-line Gene object.

**Comment by reece** [comment]
We've talked about this extensively at least twice before. We decided against it for this iteration. Let's please not revisit yet again until 1.3.

**Comment by ahwagner** [comment]
Sure, sounds good. Added to the v2-dev milestone.
