### ISSUE TITLE
Create a Google Protocol Buffer artefact of the VRS schema

### ISSUE THREAD

**Issue by ahwagner** [ga4gh/vrs#299]
Issue for tracking progress on a .proto file for VRS.

**Comment by larrybabb** [comment]
per @reece this should be tracked as a separate project. @ahwagner will ultimately move the branch from here into another repo at that point this will be closed.

**Comment by ahwagner** [comment]
this was moved to a separate repo; see https://github.com/ga4gh/vrs-protobuf
