### ISSUE TITLE
Allele Normalization

### ISSUE THREAD

**Issue by ahwagner** [ga4gh/vrs#304]
We need to refine Allele Normalization in VRS v1.2 to account for various sequence expression types.

The following was discussed in the 5/24/21 VRS call:

- Normalize LiteralSequenceExpression as SequenceState was normalized
- When using a LiteralSequenceExpression within RepeatedSequenceExpression AND a Number value for Count attribute
  - Convert to a LiteralSequenceExpression 
- When using a LiteralSequenceExpression within RepeatedSequenceExpression AND a non-Number value for Count attribute
  - Normalization by subunit (suggested but largely undiscussed)
- When using DerivedSequenceExpression (alone or within RepeatedSequenceExpression), return as-is

**Comment by ahwagner** [comment]
In discussing further with @larrybabb, we believe it is more correct to not translate between expression types. In the case of a RepeatedSequenceExpression, normalization should refine the SequenceLocation to the entire repeated subunit range found in the reference, analogous to the fully-justified normalization for LiteralSequenceExpressions.

**Comment by reece** [comment]
Totally agree. Normalization should > adjust values but not types
