### ISSUE TITLE
Update class diagrams

### ISSUE THREAD

**Issue by ahwagner** [ga4gh/vrs#310]
Current and future class diagrams for v1.2 need updating.

**Comment by reece** [comment]
@larrybabb @ahwagner 

https://app.diagrams.net/#G1Qimkvi-Fnd1hhuixbd6aU4Se6zr5Nc1h

![image](https://user-images.githubusercontent.com/109453/121285150-ba38d800-c892-11eb-99b1-1b1552c315fa.png)
