### ISSUE TITLE
What papers/recommendations/resources available to learning/applying VRS?

### ISSUE THREAD

**Issue by larrybabb** [ga4gh/vrs#311]
_This question was raised by a registrant to the June 2, 2021 GHIF VRS Webinar. Here are the [recording](https://youtu.be/kS8Sr84-8do) and [slides](https://docs.google.com/presentation/d/1t8AEJ-QPRYaMV4OgpmGIaQuOppw0Uc7YEpJALQNDSJo/edit?usp=sharing) from the Webinar_ 

1. [GA4GH Variation Representation Specification](https://vrs.ga4gh.org/en/stable/#)
   * The Appendices are particularly useful to gaining insights to the project from design principles to process
2. [VRS Git Repo & Issues](https://github.com/ga4gh/vrs)
3. Manuscript (preprint) [The GA4GH Variation Representation Specification (VRS): a Computational Framework for the Precise Representation and Federated Identification of Molecular Variation](https://www.biorxiv.org/content/10.1101/2021.01.15.426843v1)
    * pending publication in Cell Genomics.
4. [VRS-python Notebooks](https://github.com/ga4gh/vrs-python/tree/main/notebooks) 
    * a python reference library with jupyter notebooks containing examples.
5. [VRS Implementation Projects-current/pending](https://docs.google.com/spreadsheets/d/1pAXsHD_qxEgfpyv53ZVvR_B2En5dEA6iPhAHpFIXgoM/edit#gid=0)
6. [VRS Webinar and Slides](https://www.ga4gh.org/implementation/) under the GHIF Workshop Series banner.

**Comment by reece** [comment]
Added to the FAQ. Leaving open because we should figure out where/how to advertise this question.

**Comment by reece** [comment]
Rolled into #242 and #328. Closing here.
