### ISSUE TITLE
What existing tools can help bridge single-location variants and genotypes with VRS?

### ISSUE THREAD

**Issue by larrybabb** [ga4gh/vrs#313]
_This question was raised by a registrant to the June 2, 2021 GHIF VRS Webinar. Here are the [recording](https://youtu.be/kS8Sr84-8do) and [slides](https://docs.google.com/presentation/d/1t8AEJ-QPRYaMV4OgpmGIaQuOppw0Uc7YEpJALQNDSJo/edit?usp=sharing) from the Webinar_

The registrant that raised this question referenced the current challenges they were having with variation representation as follows:
1. Lack of representation of ref alleles in ClinGen Allele Registry & other dbs
2. Lack of ability to represent single-location genotypes succinctly, accurately, and/or in human-friendly format

Our initial response is...
In regards to the main question above, we believe the use of the VRS-python library and it's supporting libraries found in BioCommons github repo for managing reference sequences are useful tools that have been put into practice today which would help begin to bridge the relationship between single-location variants and genotypes.

The bigger issue may be understanding and defining precisely what is meant by *single-location variants* vs *single-location genotypes*.  I assume this is the difference between a simple allele (in VRS terms) and a simple genotype (in VCF terms). VCF represents changes at a specific location with phasing information to produce what some may consider a genotype representation at a single-location. 

VRS has been working on defining a genotype model since v1.0, but has deferred this due to various complexities and priorities in establishing some more fundamental principles. Now that we have defined the separation of variation that is either Molecular or Systemic in nature we are able to discern the requirements of genotype based on it's systemic nature in the genome.  Single-location variants or alleles are molecular in nature (or belonging to a single copy of a molecular sequence) as we've defined this in VRS. Our v1.2 introduces the Systemic concept and defines Copy Number as the first form of variation in VRS under this concept. 

Genotypes will be comprised of Alleles and we intend to complete a robust specification of Genotype in the forthcoming 1.3 release of VRS. 

In the end, I don't currently have a great answer to your question in terms of using existing tools to bridge the variation to genotype at a single location question other than using tools like VRS-python and the VRS APIs provided by the ClinGen Allele Registry. I welcome other's suggestions.

In regards to your challenges (here are my specific replies)....
1. Lack of representation of ref alleles in ClinGen Allele Registry & other dbs
   * The [ClinGen Allele Registry](http://reg.clinicalgenome.org) does support ref alleles. It is possible you may not be registering or searching for them using the proper representation. You can try the following HGVS expression to see how the CAR provides support for ref alleles ...  [NM_002496.3:c.64C=](http://reg.clinicalgenome.org/redmine/projects/registry/genboree_registry/allele?hgvsOrDescriptor=NM_002496.3%3Ac.64C%3D)
2. Lack of ability to represent single-location genotypes succinctly, accurately, and/or in human-friendly format
    * As I stated above this is a challenge that the VRS WG is still tackling, but we will not address the "human-friendly" format as this is outside of VRS's objectives. VRS is a computational format.  I defer to HGVS, but I assume this is the format that you are concerned with as it does get complex when dealing with genotypes and loses some of it's human-friendliness.

Again, we welcome others to participate in the discussion if there are additional comments, information or thoughts that could be helpful to share.

**Comment by reece** [comment]
Added to FAQ. Closing.
