### ISSUE TITLE
How do you communicate the uncertainty about variants meaningfully to other providers?

### ISSUE THREAD

**Issue by larrybabb** [ga4gh/vrs#314]
_This question was raised by a registrant to the June 2, 2021 GHIF VRS Webinar. Here are the [recording](https://youtu.be/kS8Sr84-8do) and [slides](https://docs.google.com/presentation/d/1t8AEJ-QPRYaMV4OgpmGIaQuOppw0Uc7YEpJALQNDSJo/edit?usp=sharing) from the Webinar_

This is a fundamental aim that VRS is hoping to rectify. Variation ambiguity is a big challenge and presents a risk to the use of genetics in clinical care. VRS is systematically approaching the building of the specification to provide a computationally precise way to represent variation. That statement means much more than simply being able to precisely represent a change on a precise sequence at a precise location. 

_It also means that producers and consumers of VRS concepts can represent the ambiguity of their variation precisely._

In v1.2 we have begun to introduce the ability to represent *DerivedSequenceExpressions* and *Ambiguous Range* data types to support the practice of defining variants with ambiguous start and end points for large insertions or deletions that are produced by certain assay technologies. These data types can also support min and max values for ranges of repeated sequences or copy counts when the producer only has a range that can be specified or because a range is used to define the closed or open range of copies for a given copy number variant. These are practical needs that are used to define variation that is used to collect knowledge even though the variation is not precisely defining a single variant. 

We have been collecting use cases and requirements for many years and foresee the need to build on a notion of *categorical variation* which will enable variant scientists, clinicians, researchers and other domain experts to define a variation concept that may define the criteria for a larger scope of variants that all have a common characteristic useful to science and healthcare.

We presume that when producers generate variation with VRS they will be able to be as precise or ambiguously precise as they choose making it much more intentional to support their exact meaning of the variation they share with other providers.

**Comment by reece** [comment]
Added to FAQ. Closing.
