### ISSUE TITLE
How do you represent different types of variation in a unified way (e.g. gene fusions)?

### ISSUE THREAD

**Issue by larrybabb** [ga4gh/vrs#315]
_This question was raised by a registrant to the June 2, 2021 GHIF VRS Webinar. Here are the [recording](https://youtu.be/kS8Sr84-8do) and [slides](https://docs.google.com/presentation/d/1t8AEJ-QPRYaMV4OgpmGIaQuOppw0Uc7YEpJALQNDSJo/edit?usp=sharing) from the Webinar_

The *unified way* in VRS terms means that we use a common schema to build the components that are shared across the various types of variation. By providing a unified computational information model, schema and normalization specification for all types of variation it provides the opportunity for high-order tooling to be built to address the *unification* question.  

Each data type in VRS is designed from the most atomic perspective and reused as more complex concepts of variation are added to the VRS specifications. Gene fusions are planned for the v1.3 release which is begin developed in the 2nd half of 2021. Gene fusions will most likely reuse many of the concepts already developed and available in VRS with the addition of new concepts to support the various levels of specificity and ambiguity that we all know as gene fusions.

**Comment by reece** [comment]
Added to FAQ. Closing.
