### ISSUE TITLE
How do you represent genotypes, especially for mosaicism and somatic variants (multi-ploidy)?

### ISSUE THREAD

**Issue by larrybabb** [ga4gh/vrs#316]
_This question was raised by a registrant to the June 2, 2021 GHIF VRS Webinar. Here are the [recording](https://youtu.be/kS8Sr84-8do) and [slides](https://docs.google.com/presentation/d/1t8AEJ-QPRYaMV4OgpmGIaQuOppw0Uc7YEpJALQNDSJo/edit?usp=sharing) from the Webinar_

VRS v1.2 (planned release June 2021) is the first version that establishes the notion of "systemic" variation or variation in the context of a system (cellular or genome in the case of genotype). Molecular variation is variation in the context of a single molecule or sequence. The copy number variation in v1.2 is our first type of systemic variation. We have been working towards releasing Genotype (another type of systemic variation) for v1.3 (end of 2021).  

The genotype design will most likely need to involve the notion of ploidy and will also need to support somatic variation concepts like mosaicism. We would encourage participation in our VRS working group meetings to assure your use cases and requirements are properly captured and addressed. We do have a fairly broad and active participation but we do need new members to either participate by attending meetings, adding issues or requirements in this github repo and/or participating in review of forthcoming releases via the Github PR (pull request) process in this repo.

**Comment by reece** [comment]
Answered in FAQ. Closing.
