### ISSUE TITLE
How do you handle variant representations and annotation across multiple transcripts and reference builds?

### ISSUE THREAD

**Issue by larrybabb** [ga4gh/vrs#317]
_This question was raised by a registrant to the June 2, 2021 GHIF VRS Webinar. Here are the [recording](https://youtu.be/kS8Sr84-8do) and [slides](https://docs.google.com/presentation/d/1t8AEJ-QPRYaMV4OgpmGIaQuOppw0Uc7YEpJALQNDSJo/edit?usp=sharing) from the Webinar_

VRS refers to variant annotation as the association of *any* attributes or data that do not *define* the variation computationally. 

So what does it mean to *define* the variation computationally? 

VRS works to provide the lowest level of computational meaning of variation to insure a consistent and accurate sharing of that variation between computational systems. VRS is intentionally ignorant of the biological concepts beyond the basic idea of a molecule or feature form (i.e. a residue sequence or chromosomal cytobands and a gene id, thus far), a sequence or cytoband location, the state at that location and/or the copies of it. 

Dealing with specific transcript forms have been considered outside the scope of VRS and would instead be handled by the work being dealt with by the GA4GH GKS Variant Annotation or Sequence Annotation subgroups. 

That said, there has been numerous discussions and remaining open considerations for including a computational form of transcripts in VRS. But, even if this does occur, it would not likely be akin to the simple mapping of various authoritative transcript accession ids, but instead more of a computational representation that would allow higher-order systems to do this mapping more accurately and consistently when needed in applications.

In the same manner, supporting the mapping of variation between multiple genome reference builds is a higher-order implementation decision. VRS does not set or adopt a policy on genome build mapping or alignment. Instead the computational representation of variation in VRS for specific genome builds could and should be used by tools and services that establish these policies. [ClinGen Allele Registry](http://reg.clinicalgenome.org/redmine/projects/registry/genboree_registry/landing) is a example of an open *de-duplication* allele registry that has a policy for presenting a unified representation of all genomic builds and aligned transcripts and their protein variants.  ClinVar, dbSNP, VICC and other variant knowledge-bases and tools also support the notion of a *canonical* representation of all the variation that aligns and derives from a single allele in a given organisms genome (namely human genomes).

**Comment by reece** [comment]
Added to the FAQ. Closing.
