### ISSUE TITLE
How do you deal with Variants that need to hold large amounts of data?

### ISSUE THREAD

**Issue by larrybabb** [ga4gh/vrs#318]
_This question was raised by a registrant to the June 2, 2021 GHIF VRS Webinar. Here are the [recording](https://youtu.be/kS8Sr84-8do) and [slides](https://docs.google.com/presentation/d/1t8AEJ-QPRYaMV4OgpmGIaQuOppw0Uc7YEpJALQNDSJo/edit?usp=sharing) from the Webinar._

I presume this question or challenge was shared with the VRS team on the VRS Webinar registration form because of the common challenge many of us address when packaging data related to a given variant. If that is an improper assumption please provide more clarity.

What does it mean to provide large amounts of data with a variant? 

What I commonly experience when a system sends a variation to another system (or on a report) is the need to share the different HGVS representations that may be derived from the originally measured variation. The gene or genes, the transcripts, the accession identifiers for the sequences, the prediction or population frequency data and on and on...  It may also be data related to the reads or quality of the variant or case level interpretations or variant-level classifications in the context of somatic or germline interpretation protocols like the AMP/CAP/ASCO or ACMG guidelines, respectively.

All of this "data" falls under the notion of [Variation Annotation](https://github.com/ga4gh/va-spec) or VA . There is a separate VA subgroup in GKS and they are working to define and use VRS-based statements to provide a way to consistently represent different types of variation.

Additionally, there is a [VRSATILE](https://vrsatile.readthedocs.io/en/latest/) implementation guide being developed with VRS to provide engineers with alternative options for sharing different levels of annotations in a consistent manner while providing the flexibility to mix-in custom data as needed by implementers during real-world system development.

VRS does not concern itself with "Annotation" or ancillary data that is not computationally required to define the variation itself.

**Comment by reece** [comment]
Added to FAQ. Closing.
