### ISSUE TITLE
Update examples using validation tests

### ISSUE THREAD

**Issue by ahwagner** [ga4gh/vrs#323]
Added [todo in documentation](https://github.com/ga4gh/vrs/commit/916c59a171bd5f2211d4e96008c4bd4cf735a5d8). The digests in the Haplotype example are based on an outdated version of Haplotypes using SimpleInterval instead of the new SequenceInterval. While the in-line example has been updated to reflect the newer data classes, the reference example is not updated.

This is a low-priority issue.

**Comment by reece** [comment]
I'll take this. I'm ~50% done updating the validation tests and examples for #258, which have high overlap to help ensure correctness.

**Comment by reece** [comment]
Closed in 1e63b8c
