### ISSUE TITLE
Remove "Abundance" from diagrams

### ISSUE THREAD

**Issue by ahwagner** [ga4gh/vrs#324]
Abundance is a conceptual grouping that does not serve much purpose (yet). I've removed it to simplify our model somewhat in #322; if those changes are agreed on we will need to update the schema diagrams (present and future) to remove this extra abstraction layer.

**Comment by reece** [comment]
+1 for removing.

**Comment by ahwagner** [comment]
Remove extra whitespace at bottom of figure and address missing property from #334.
