### ISSUE TITLE
DerivedSequenceExpression.reverse_complement fact of fiction?

### ISSUE THREAD

**Issue by larrybabb** [ga4gh/vrs#340]
[DerivedSequenceExpression](https://github.com/ga4gh/vrs/blob/abd88cd5a99cef598de6f0e4b70b028ebbde2888/docs/source/terms_and_model.rst#derivedsequenceexpression) has a `reverse_complement` attribute in the example but it is not specified in the table containing the definition of the `Information Model`.

Should it be removed from the example or specified in the Information Model?

**Comment by ahwagner** [comment]
Thanks Larry. I think the docs need another round of cleanup to address this and other issues you have raised. Hopefully our work in a single source-of-truth (SOT) document from VRSATILE is translatable here and can help us resolve a lot of this automatically.

Our current SOT should be the JSON Schema, and [we did include](https://github.com/ga4gh/vrs/blob/1.2.0/schema/vrs.json#L666-L668) `reverse_complement` in v1.2.0; so it sounds like this is a documentation issue.

**Comment by larrybabb** [comment]
closing this as no one has raised concerns and as you indicated our VRSATILE work demonstrates the use of `reverse_complement` ideally we would do a patch release of the 1.2 documentation, but at this time 1.2 is obsolete so I don't see the need.
