### ISSUE TITLE
species vs species_id in ChromosomeLocation

### ISSUE THREAD

**Issue by korikuzma** [ga4gh/vrs#355]
In [terms_and_model.rst](https://github.com/ga4gh/vrs/blob/main/docs/source/terms_and_model.rst), the field is `species`. In the [vrs schema](https://github.com/ga4gh/vrs/blob/main/schema/vrs.yaml#L217), the field is `species_id`. @ahwagner Is the field actually `species_id` and it's just a typo in the docs?

**Comment by ahwagner** [comment]
The field is indeed supposed to be `species_id`; just another reason why we are transitioning over to the meta-schema / single definition tooling for both docs and schema.

Thank you for pointing this out; as it so happens I have been working on the VRS meta-schema transition today and will do `Locations` next to cover this.

**Comment by korikuzma** [comment]
This is stale. We can close.
