### ISSUE TITLE
Revise CopyNumber definition

### ISSUE THREAD

**Issue by ahwagner** [ga4gh/vrs#359]
>Should this be re-written as...
>
> > The 'absolute' count of discrete copies of a MolecularVariation, Feature, SequenceExpression or CURIE reference contained within a system (i.e. genome, cell, etc...).
>
>I'm not sure the current phrasing is clear. What does 'to any of these' mean in the context of count of discrete copies of a subject...?

_Originally posted by @larrybabb in https://github.com/ga4gh/vrs/pull/356#r758667366_

**Comment by ahwagner** [comment]
Current:
> The count of discrete copies of a subject :ref:`MolecularVariation`,
> :ref:`Feature`, :ref:`SequenceExpression`, or a :ref:`CURIE` reference
> to any of these

The proposed revision covers 2 related issues:

1. Clarification that this is an _absolute_ copy number statement; this is indeed the intent of the CopyNumber class
2. CURIE reference only applies to _some_ of the potential subjects

**Comment by mbaudis** [comment]
@ahwagner Sure about the `absolute`? Then you _always_ need base ploidy etc.

**Comment by ahwagner** [comment]
@mbaudis yes, for the _current_ class. We definitely need a RelativeCopyNumber class as well.

**Comment by mbaudis** [comment]
@ahwagner ... and take my _always_ with some Himalayan salt - sure, true for full coverage of options :-)
