### ISSUE TITLE
Revise CytobandInterval definition

### ISSUE THREAD

**Issue by ahwagner** [ga4gh/vrs#361]
>For consistency this should be stated similarly to SequenceLocation "the span on a chromosome bounded by ctyoband endpoints" or something to that affect. It is not a region or a cytoband itself. It is an "interval" that is strictly used by the ChromosomeLocation to define a location on a chromosome based on cytoband nomenclature.

_Originally posted by @larrybabb in https://github.com/ga4gh/vrs/pull/356#discussion_r758678534_

**Comment by ahwagner** [comment]
SequenceLocation definition:
> A :ref:`Location` defined by an interval on a referenced :ref:`Sequence`.

SequenceInterval definition:
> A SequenceInterval represents a span on a :ref:`Sequence`. Positions are
> always represented by contiguous spans using interbase coordinates or
> coordinate ranges.

CytobandInterval definition:
> A contiguous region specified by cytobands. The region includes
> the constituent regions described by the start and end cytobands,
> as well as any intervening regions.

Proposed revision to CytobandInterval:
> A contiguous span on a chromosome defined by cytoband features.
> The span includes the constituent regions described by the start and
> end cytobands, as well as any intervening regions.

**Comment by ahwagner** [comment]
Proposed resolution: implement as suggested.

**Comment by mbaudis** [comment]
+1

**Comment by larrybabb** [comment]
This was merged. should have been closed then.
