### ISSUE TITLE
Multiple repeat expansions in VRS

### ISSUE THREAD

**Issue by ahwagner** [ga4gh/vrs#363]
In communication from @rhdolin:

> Rachel Kutner from Epic has put together a thoroughly [researched proposal](https://jira.hl7.org/browse/FHIR-34418) for representing repeat expansions in FHIR Genomics. We've gone over the VRS model, and I had a question.
> 
> In scenarios where you have mixed / multiple repeats (e.g. 'CTG[30]CAG[50]' or 'NM_004643: GCG[6]GCA[3]GCG[1]'), how would VRS represent the multiple sequential repeats? Would you, for instance, create a RepeatedSequenceExpression for each of the repeats, and then group them together in a haplotype? Or is there some other approach you'd take in VRS?
> 
> Thanks!

Direct link to examples: https://jira.hl7.org/secure/attachment/19521/19521_Repeat+Expansion+HL7+Proposal.pdf

**Comment by ahwagner** [comment]
I propose that we address mixed repeats (and other related scenarios) using a new `SequenceExpression` subclass, `ComposedSequenceExpression`. The proposed class definition follows.

## ComposedSequenceExpression
An expression of a sequence composed from multiple sequence expression components.

### Constraints
At least one sequence expression component is not a `LiteralSequenceExpression`.

### Information Model
| Field | Type | Limits | Description |
| --- | --- | --- | --- |
| type | string | 1..1 | The ComposedSequenceExpression type. MUST be `ComposedSequenceExpression`. |
| components | `SequenceExpression` | 2..m | An ordered list of `SequenceExpression` components used to construct the `ComposedSequenceExpression`. |

### Example
An example sequence expression for *OPMD allele -1* from Rachel Kutner's [researched proposal](https://jira.hl7.org/browse/FHIR-34418) using this class:
```JSON
{
  "type": "ComposedSequenceExpression",
  "components": [
    {
      "type": "RepeatedSequenceExpression",
      "seq_expr": { "type": "LiteralSequenceExpression", "value": "GCG" },
      "count": { "type": "Number", "value": 11 }
    },
    {
      "type": "RepeatedSequenceExpression",
      "seq_expr": { "type": "LiteralSequenceExpression", "value": "GCA" },
      "count": { "type": "Number", "value": 3 }
    },
    {
      "type": "RepeatedSequenceExpression",
      "seq_expr": { "type": "LiteralSequenceExpression", "value": "GCG" },
      "count": { "type": "Number", "value": 1 }
    }
  ]
}
```

**Comment by bheale** [comment]
Works well for communicating/representing the sequence. But could you show me how the composedSequence's relationship to a chromosomal position would be represented in your model?

Thanks!
Bret

**Comment by bheale** [comment]
What is the artificial (or generally acceptable) boundary between CNV versus tandem repeats? Or could the structure here also cover communication of a CNV where the sequence of each copy of X is known? E.g. a gene duplication event where the duplicates do not share the exact same sequence?

**Comment by ahwagner** [comment]
> Works well for communicating/representing the sequence. But could you show me how the composedSequence's relationship to a chromosomal position would be represented in your model?

@bheale no problem.  The above `ComposedSequenceExpression` is used wherever a `SequenceExpression` (the parent class) is allowed. In the case of the above *OPMD Allele -1*, it would be used inside of an [Allele](https://vrs.ga4gh.org/en/latest/terms_and_model.html#:~:text=state-,Sequence%20Expression,-%7C%20SequenceState%20(deprecated)) to describe the `state`.

Represented on the transcript sequence NM_004643.3, the full Allele would look like this:
```JSON
{
  "type": "Allele",
  "location": {
    "type": "SequenceLocation"
    "sequence_id": "ga4gh:SQ.sH4gymNtL5nxNdTE3evfxzZa4dg3fqDz",
    "interval": { 
      "type": "SequenceInterval", 
      "start": { "type": "Number", "value": 3  },
      "end":   { "type": "Number", "value": 21 }
    }
  },
  "state": {
    "type": "ComposedSequenceExpression",
    "components": [
      {
        "type": "RepeatedSequenceExpression",
        "seq_expr": { "type": "LiteralSequenceExpression", "value": "GCG" },
        "count": { "type": "Number", "value": 11 }
      },
      {
        "type": "RepeatedSequenceExpression",
        "seq_expr": { "type": "LiteralSequenceExpression", "value": "GCA" },
        "count": { "type": "Number", "value": 3 }
      },
      {
        "type": "RepeatedSequenceExpression",
        "seq_expr": { "type": "LiteralSequenceExpression", "value": "GCG" },
        "count": { "type": "Number", "value": 1 }
      }
    ]
  }
}
```

**Comment by ahwagner** [comment]
@larrybabb: we should consider adding indices to JSON arrays where order is meaningful
@tnavatar: this would make everyone's life easier in RDF land
Andreas & Andy: VRS is verbose, why not just do it?
Bob Freimuth: +1

We should introduce a special variable "index" that allows us to always represent these types of arrays consistently for computed identifier construction. This may actually require a special data class that allows us to explicitly contain other objects; so we can have ordered, identifiable objects.

It should be a red flag if there is no index special class in an array and it allows for non-identifiable objects.

**Comment by ahwagner** [comment]
We should have documentation to explain when to use this and why.

@larrybabb proposal: we should constrain this to _only_ repeatedsequenceexpressions as components. Unanimous agreement to start constrained on 12/13 call.

**Comment by ahwagner** [comment]
I think I need to better understand the issue behind the [above proposal](https://github.com/ga4gh/vrs/issues/363#issuecomment-992704889). It seems to me (and I believe that @reece and @bheale would agree) that since this is [definitional behavior for JSON arrays](https://json-schema.org/draft/2020-12/json-schema-core.html#:~:text=array%3A,JSON%20%22array%22%20value), the introduction of a specialized "ordered container class" is effectively extra weight on what is already explicitly meant by an Array.

**Comment by reece** [comment]
Yes, I agree with @ahwagner: are already ordered, so a new container that does the same thing makes the new container incompatible with arrays and, at the same time, creates new obligations for implementations to ensure that the same index isn't used more than once.

**Comment by bheale** [comment]
Does G4GH use XML representations as well as JSON?

**Comment by ahwagner** [comment]
GA4GH data standards come in a variety of representations; Google Protocol Buffers (protobuf), JSON Schema, and file-based are a few. The VRS Schema is implemented in JSON Schema, and consequently VRS JSON is the authoritative form and basis for the computed identifier algorithm.

The VRS information model has also been implemented as protobuf in the past, but I do not know of an XML implementation out there. However, I believe that even if there were an XML implementation, there would still not be a need for an explicit `index` element or attribute; [XML element order in lists is assumed to be preserved](http://lists.xml.org/archives/xml-dev/201003/msg00045.html).

**Comment by bheale** [comment]
Thanks! Great link. Love the community. Happy New yearish, Bret

**Comment by larrybabb** [comment]
@ahwagner While it is great that JSON offers definitional behavior for arrays, we use a form of Canonical JSON tooling to sort our json including the array elements before digesting. This json canonicalization would mess with the producers "implicit" ordering that would be assumed by the array ordering and thus risk misrepresenting the array order that is intended. By adding the index (which is arguably very light weight) we reduce the assumptions and risks that ordering is misconstrued.

**Comment by ahwagner** [comment]
I had the same concern, but as it turns out @reece was ahead of the ball on this and our serialization strategy [only sorts if the array contains ids or digests](https://vrs.ga4gh.org/en/stable/impl-guide/computed_identifiers.html#:~:text=order%20arrays%20of%20digests%20and%20ids%20by%20Unicode%20Character%20Set%20values); this is also how it is implemented in vrs-python.

**Comment by larrybabb** [comment]
That's great. However, I am still a little uncomfortable with relying on the physical positional order in the message's array is significant, particularly when sharing with external systems. If other's are comfortable with the reliance on understanding that arrays in our messages are strictly ordered then I can capitulate.

**Comment by ahwagner** [comment]
Still needed: documentation. Reopening to address prior to 1.3rc

**Comment by larrybabb** [comment]
closing this since it was merged and the subsequent documentation task was added to a new ticket.
