### ISSUE TITLE
Breakends and positions

### ISSUE THREAD

**Issue by ahwagner** [ga4gh/vrs#365]
One concept that will need to be considered as we approach fusion & SV representation is the notion of a _breakend_, a _position_ on a sequence representing some indefinite amount of sequence to the left or right of the position.

The position is contrasted from an interval by having a single Number/Range value instead of both a start and end Number/Range value.

**Comment by cmprocknow** [comment]
I think we can represent this already using IndefiniteRange, right?:

	{
		"interval": {
			"end": {
				"type": "Number",
				"value": 44908822
			},
			"start": {
				"type": "Number",
				"value": 44908821
			},
			"type": "SequenceInterval"
	},
		"sequence_id": "ga4gh:SQ.IIB53T8CNeJJdUqzn9V_JnRtQadwWCbl",
		"type": "SequenceLocation"
	}
