### ISSUE TITLE
Replace single-value enums in abstract classes with direct refs

### ISSUE THREAD

**Issue by ahwagner** [ga4gh/vrs#368]
Both `SystemicVariation` and `Feature` are abstract classes with only a single child class. In these cases, it would be cleaner to drop the `oneOf` and instead reference the child class directly.

@bwalsh @jsstevenson @korikuzma

**Comment by mbaudis** [comment]
@ahwagner ATM this would make sense for `SystemicVariation`; but then would need to change again when other options are added... Right now I could e.g. envision CN-LOH (which, though, could be CNV child) or complex regional events (chromothripsis ...) to be added as options. Similar for `Feature` ...

IMO I would keep the current structure *but* document the placeholder nature.

**Comment by ahwagner** [comment]
Unanimous for leaving as is.
