### ISSUE TITLE
Should DerivedSequenceExpression contain a reverse_complement flag?

### ISSUE THREAD

**Issue by larrybabb** [ga4gh/vrs#370]
In the [current v1.2 spec](https://vrs.ga4gh.org/en/stable/terms_and_model.html#derivedsequenceexpression) the information model makes no reference to a `reverse_complement` flag attribute, but the example message shows it. 

I believe it shouldn't be in the example. In either case it should be fixed to be consistent.

**Comment by ahwagner** [comment]
this has been addressed in the 1.2.1 pull requests.
