### ISSUE TITLE
Confusing text in sha512t24u description

### ISSUE THREAD

**Issue by jmarshall** [ga4gh/vrs#386]
The opening paragraph of the [Truncated Digest (sha512t24u)](https://vrs.ga4gh.org/en/stable/impl-guide/computed_identifiers.html#truncated-digest-sha512t24u) section says:

> The sha512t24u truncated digest algorithm [[Hart2020]](https://vrs.ga4gh.org/en/stable/impl-guide/computed_identifiers.html#hart2020) computes an ASCII digest from binary data. The method uses two well-established standard algorithms, the [SHA-512](https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.180-4.pdf) hash function, which generates a binary digest from binary data, and **[Base64](https://tools.ietf.org/html/rfc4648) URL encoding**, which encodes binary data using printable characters. [Emphasis added]

This is confusingly written, as “[URL encoding](https://en.wikipedia.org/wiki/URL-encoding)” refers to percent encoding of URLs, which is a different encoding unrelated to the base64 variant used here.

It would be better to use the RFC 4648 terminology for this encoding: either “…and Base64 URL/Filename-Safe encoding, which encodes binary data…” or “…and base64url encoding, which…” (as is used in step 3 later in the section).

**Comment by ahwagner** [comment]
I agree, this would be a good change. Of these options, my preference would be for base64url for consistency and brevity.

**Comment by ahwagner** [comment]
This closes #386. @jmarshall your review here is welcome.
