### ISSUE TITLE
Moving to a generic TextConcept entity

### ISSUE THREAD

**Issue by ahwagner** [ga4gh/vrs#395]
> @ahwagner Here's a whopper.  I think we should consider "Text" or "VariationText" to be a universal and ambigous thing that can be used for any "text string" not just for variation. This would allow us to using it for "Conditions", "Drugs" and other value-object-like domain entities that we will be using.  Just because it's under the VRS umbrella does not mean it is specialized to be a Variation (I think).  Unless we think that subclassing these utilitye "text" concepts to domain specific types (i.e. ConditionText, DrugText, etc...) is important for folks to know that it meant to be a Condition, Drug, etc... .  Just thinking that if we wanted to do this then we would change the prefix to "TX" or "TXT" and modify the documentation to emphasize that it is truly a utility class that open to interpretation and will require the producer and consumer to "imply and infer" it's meaning (which is what they do anyway).

_Originally posted by @larrybabb in https://github.com/ga4gh/vrs/pull/394#discussion_r925537355_

**Comment by ahwagner** [comment]
> I'm fine with expanding the scope as proposed by Alex.
> 
> The original intention was to be able to store something that is semantically variation but not yet interpretable by VRS, such as "loss of maternal copy of PTEN" or "deletion of at least two prime-numbered exons of EGFR" or whatever.
> 
> However, there's no way to enforce that, and it's very unclear that there's any benefit to having a blob that's supposed to be variation-like but might be a cookie recipe.
> 
> So, might as well just go with the idea that it's a totally unvalidated blob.

_Response posted by @reece in https://github.com/ga4gh/vrs/pull/394#discussion_r927211633_

**Comment by ahwagner** [comment]
@larrybabb I think your idea of a generic Text / TextConcept entity is fine, but we will want to just have TextVariation inherit from that class in VRS if TextConcept is abstract, or remove TextVariation from VRS if TextConcept is concrete. I think we ultimately will want to remove `Gene` as well and have a similar concept for more generic typed domain references.

**Comment by ahwagner** [comment]
The issue of `Text` as a Utility Variation concept or as a general concept should be resolved prior to release of a VRS 2.0 release candidate.

**Comment by larrybabb** [comment]
This was resolved in v2.0-alpha by presuming we would represent "ambiguous" or "text" based variation in our CategoricalVariation subtype called `DescribedVariation`. This removes this non-computational issue from VRS where it really never belonged.
