### ISSUE TITLE
Deprecate CopyNumber

### ISSUE THREAD

**Issue by ahwagner** [ga4gh/vrs#396]
> @ahwagner should we mark "CopyNumber" obsolete and make an annotation about the forthcoming Absolute and Relative CopyNumber?
I know this is all about Genotype, but maybe there's an opportunity to inform folks about the "dangers" of using CopyNumber that is definitely in a "Draft" maturity state.

_Originally posted by @larrybabb in https://github.com/ga4gh/vrs/pull/394#discussion_r925532651_

**Comment by larrybabb** [comment]
Yes. We should clarify that it was a draft and we should reference the new concepts. Communication and transparency are paramount imo

**Comment by ahwagner** [comment]
Today @larrybabb and I discussed this issue and decided that–for now–we have no plans to add RelativeCopyNumber support to VRS v1, and leave this as a v2+ feature.

**Comment by ahwagner** [comment]
This decision was reversed in conversation with @larrybabb and @andreasprlic on 10/6.
