### ISSUE TITLE
SV SIG – Variant calling benchmarking use case

### ISSUE THREAD

**Issue by Rapsssito** [ga4gh/vrs#422]
First of all, I want to give a bit of context about me and my background. My name is Rodrigo Martín and I work as a research engineer at Barcelona Supercomputing Center (BSC) in Spain. I originated from software engineering, so if I misname, confuse or just say something blatantly wrong, feel free to correct me because I am still working to understand the biology part of this. I believe I can give some insight into possible use cases for VR. Currently, we are working on a benchmarking platform for somatic variant calling, specially targetted to SV calling. For this reason, I work with a lot of VCF/VCF.GZ/BCF files from a lot of different sources and variant callers, trying to find differences/similarities in order to provide information about recall/precision performance, possible improvements, degree of similarity, etc. We only work with somatic variants, but I believe some of these issues might apply to other fields.

With the context out of the way, I want to say congratulations to Daniel for the presentation. Eventhough I did not understand all possible scenarios you proposed, I really liked it because it was thoroughly researched and explained. You proposed two approaches "narrow" vs "wide" and I wanted to make my case for the "narrow" approach. I am fairly new to this working group, so apologies in advance if I missed the whole point and feel free to ignore everything I say.

When benchmarking variant callers, we wanted to go with to the "narrow approach" of looking at exactly what the variant callers output: breakends. It was much easier said than done because of a number of problems we encountered with the VCF specification: the brackets are confusing, the existence of prefixes and suffixes add unnecessary complexity, the biological meaning behind the notation is not clear, its actual state in the alignment file is not clear, two entries in the same file actually represent the same breakend (which makes one of them redundant), etc. This problem is even exacervated by the existence of an alternative notation (shorthand notation `<DEL>`, `<INV>`...) that does not even match with the breakend notation in the case of `<INV>` (as pointed out by Daniel). In a variant representation schema (like VRS), these problems should not exist. We should be able to compare the breakends coming from different variant callers without the necessity to take into account redundancies, different ways to represent the same variants, etc. This also affects the community in a large scale, as many scientist do not fully understand the current VCF specification for SV breakend notation (due to its huge complexity), and thus shun VCF in favor of BED or just ignore SV altogether.

In our specific use case, we needed to have an specification that gives an atomic, deterministic and non-redudant way to represent variants. For this reason, I actually "forced" myself to create a preprocessing tool to abstract the inherent complexity of the VCF specification, specially for SVs: https://github.com/EUCANCan/variant-extractor. However, I believe VRS should be the ultimate solution by providing a detailed vision of what is going on in the genome (it would also be great it also removed the imaginary division between INDELs and deletions, duplications and insertions. I won't elaborate on that for now).

My suggestion for this "narrow" approach is a structure like this (it is very very very not well thought, just an example and I am not very familiar with current VRS schemas):
```json
{
    "variants/breakends/atomicthings": [
        {
            "_id": "...", // SNV (MNV could be a bunch of SNVs or edit "newSequence" and "end")
            "start": {
                "contig": "1",
                "position": "100",
                "orientation": "+"
            },
            "end": {
                "contig": "1",
                "position": "101",
                "orientation": "+"
            },
            "newSequence": "A",
            "qual": "100",
            "filter": "..."
        },
        {
            "_id": "...", // DEL (INDEL or SV, avoid different representations for the same thing)
            "start": {
                "contig": "1",
                "position": "100",
                "orientation": "+"
            },
            "end": {
                "contig": "1",
                "position": "200",
                "orientation": "+"
            },
            "newSequence": "ATCACA", // This could be empty, but it is not, that means new bases are added before the breakend
            "qual": "100",
            "filter": "..."
        },
        {
            "_id": "...", // INS (INDEL or SV, avoid different representations for the same thing). DUP could be just INS.
            "start": {
                "contig": "1",
                "position": "100",
                "orientation": "+"
            },
            "end": {
                "contig": "1",
                "position": "100",
                "orientation": "+"
            },
            "newSequence": "CCCAAATTATA",
            "qual": "100",
            "filter": "..."
        },
        {
            "_id": "...", // INV (different orientations would be different INVs)
            "start": {
                "contig": "1",
                "position": "100",
                "orientation": "-"
            },
            "end": {
                "contig": "1",
                "position": "200",
                "orientation": "+"
            },
            "newSequence": "",
            "qual": "100",
            "filter": "..."
        },
        {
            "_id": "...", // TRA
            "start": {
                "contig": "2",
                "position": "100",
                "orientation": "+"
            },
            "end": {
                "contig": "3",
                "position": "100",
                "orientation": "+"
            },
            "newSequence": "",
            "qual": "100",
            "filter": "..."
        },
        {
            "_id": "...", // Complex INDEL (del and ins)
            "start": {
                "contig": "1",
                "position": "100",
                "orientation": "+"
            },
            "end": {
                "contig": "1",
                "position": "102",
                "orientation": "+"
            },
            "newSequence": "ATCACA",
            "qual": "100",
            "filter": "..."
        },
    ]
}
```

I would also like to point out that both "narrow" and "wide" approaches could coexist (and it could even be beneficial). For instance, following my example provided above, you could have two entries, one for atomic operations (in my example it is named "variants/breakends/atomicthings") and one for the events they "create". This last entry would contain events with a reference to the atomic entries ids that originated them. Notice how my example does not say anything about what they represent (the "event" entries would elaborate on that), but just what they are.

Thanks for getting to the end of the message! I hope it helps!

**Comment by d-cameron** [comment]
> In a variant representation schema (like VRS), these problems should not exist. We should be able to compare the breakends coming from different variant callers without the necessity to take into account redundancies, different ways to represent the same variants, etc. This also affects the community in a large scale, as many scientist do not fully understand the current VCF specification for SV breakend notation (due to its huge complexity), and thus shun VCF in favor of BED or just ignore SV altogether.

Agreed. Even the problem of matching SV calls for benchmarking purposes is unnecessarily complicated in VCF and to do a half-decent job you need to write a notation normalisation library. It's an artifact of the history of VCF and not a design decision that should be repeated in VRS.

> Currently, we are working on a benchmarking platform for somatic variant calling, specially targetted to SV calling. For this reason, I work with a lot of VCF/VCF.GZ/BCF files from a lot of different sources and variant callers, trying to find differences/similarities in order to provide information about recall/precision performance, possible improvements, degree of similarity, etc. We only work with somatic variants, but I believe some of these issues might apply to other fields.

Having written a notation normalisation and benchmark frameworks myself (see BioConductor StructuralVariantAnnotation; PMC8963309; PMC6642177), I totally agree. This is why I've been strongly advocating for a 'narrow' purely breakpoint-based definition, with all higher-order classifications and structures defined on top of that.

> I would also like to point out that both "narrow" and "wide" approaches could coexist (and it could even be beneficial). For instance

This minimal definition is similar to your example. The fundamental breakpoint unit is a breakend (chr, pos, orientation) with a breakpoint defined as an (unordered) pair of breakends. There's a fair bit of additional complexity on top of this (e.g. the same rearrangement can be reported as a DUP or an INS (something that benchmarking frameworks need to handle) and even huge windows of position ambiguity even for precise variants (e.g. REF=SINE-SINE-SINE, ALT=SINE-SINE-SINE-SINE -> short read callers report DUP for first SINE, long read callers report INS after end of 3rd SINE = same haplotype, 600+bp between equivalent variants)) but we can build that on top of the fundamental basics.

Similarly, the higher-order events can be defined as the composition of these basic units. There's a whole lot of complexity here and there's multiple competing definitions of 'event' and I want VRS to be flexible enough to represent them all (e.g. simple DEL/DUP/INS/INV; partial derivate chromosome reconstructions; breakage-fusion-bridge/chromothripsis/chromoplexity (=single biological events); LINE reactivation of a particular donor site (=multiple biological events but should be able to be logically grouped together (rigma/pyro also fall into this category)). This is still somewhat of an open problem in the community so I expect it is here where the biggest struggle to define a standard the works for everyone will me.

**Comment by Rapsssito** [comment]
@d-cameron, thanks a lot for your detailed answer! I am glad we agree in the approach.

This week we had an opening discussion about this topic. We are all from different backgrounds, so we have to level the playing field for everyone. There is still a lot of confusion when it comes to defining SVs (and the differences between CNVs and SVs).

For the next meetings, I would like to push this layered approach, using the breakends as the foundation layer for everything above. I was thinking about something like this (_keep in mind I am not familiar with biology, I just know a little about variant calling, so it might not make any sense .\_._):

| Knowledge level | Layer | Example |    
| --- | ------ | --------- |
| More biological | Complex events | Reciprocal translocation (affected genes: XXX, MMM) |
| ^ | Events | TRN, TRN |
| More computational/algorithmical | Breakends | `1:100-2:200 +-`, `2:250-1:150 -+`   |                   

The events in layer `Events` would reference to the breakends from the layer `Breakends`. The complex events in `Complex events` would reference the events from the layer `Events`. This modularity will also allow for the creation of tools that target a specific layer. The clinicians would only need to check the last layer.

What do you think about this approach? Would you add more or reduce levels?

**Comment by Rapsssito** [comment]
@d-cameron, I guess we can follow this discussion in #425?
