### ISSUE TITLE
Ambiguous interpretation of variants when combining multiple reference sequence versions 

### ISSUE THREAD

**Issue by d-cameron** [ga4gh/vrs#427]
An issue has come up defining phasing of SVs. The SV phasing model needs to define an ordering of phased variants otherwise the haplotype would be ambiguous (e.g. a duplication has two SNPs, one on the first copy and one on the second copy). My proposed model for this is to define phasing as a derivate chromosome traversal order (in the earlier example a phasing ordering would be: SNP of first copy, traverse duplication breakpoint, SNP on second copy). This is fine until variant references get mixed. The particular example I'm thinking of is if a breakpoint occurs in a region that hg38 has inverted w.r.t hg19. If the VRS file contains a pre-inversion-region hg19 variant phased with the intra-inversion hg38 breakpoint, what does that imply about the genomic structure on that chromosome? Depending on the orientation on the intra-inversion breakpoint, only one of the hg19 or hg38 backbones will be a valid traversal order.

Thinking about this a bit more, this is a more general question and is actually a problem for the base VRS specifications themselves. So my question for VRS team is this: what does defining a variant w.r.t a particular reference imply about the genomic sequence and structure defined by that reference sequence?

**Comment by ahwagner** [comment]
The Haplotype model for VRS 2.0a currently handles multi-sequence Haplotypes by allowing Adjacency objects to be Haplotype members.

The question of what to do about variant calls that define Adjacencies across multiple reference assemblies is out-of-scope. VRS does not specify what reference sequences should be used by providers; and presumably if there is a dataset out there that does this they 1) have a reason for mixing references 2) have a method for resolving multiple alignment challenges of such an approach, and 3) will need to use VRS 2.x to represent the resulting structures.
