### ISSUE TITLE
2.0 alpha SV issues/clarifications

### ISSUE THREAD

**Issue by d-cameron** [ga4gh/vrs#449]
1. Haplotype

Should this be redefined as a path along a molecule?

Description needs cleanup. "Members must share the same reference sequence as adjacent members." is inconsistent with "Sequence references MUST be consistent for all members between and including the end of one Adjacency and the beginning of  another."

- `should` or `MUST` not overlap? Should means that overlapping variants are indeed valid VRS. Shouldn't adjacent overlapping alleles be a validation errors?

- How should we handle scenarios where there's a variant in a Adjacency homology region? Is the homology region defined w.r.t the reference or the resultant molecule? E.g.

```
Sequence:           GAGAAAATTTTCTTTAAAGAG
Ref homology:              ********
Left connected:     GAGAAAATTTTTTTTCCCCCCCCC
Right connected:    CCCCCCCCTTTTTTTAAAAGAG
```
The variant has to go somewhere. Multiple options:
Option A: Homology is defined w.r.t reference sequence ; Ref variants can overlap homology bounds;  Variants should be placed on the side that would make a REF call

E.g. here we should make a right ref call to prevent the snp overlapping
```
Sequence:           GAGAAAATTTTCTTTAAAGAG
Left connected:     GAGAAAATTTTTTTTCCCCCCCCC
Right connected:    CCCCCCCCTTTCTTTAAAAGAG
Left snp            GAGAAAATTTTCTTTCCCCCCCCC
                               ^
Alt homology:               *******
ref homology:               ***
```
I'm not sure we can entirely avoid variants overlapping homology bounds. We probably need to allow variant overlap with non-homology bounds so maybe Adjacency overlapping Allele isnt so much of an issue if there's not any additional ambiguity introduced.

Option B: homology is defined w.r.t molecule; Variants overlapping the homology interval are allowed

Overlapping variants are problematic as they can be represented on the left, the right, or both.

Option C: Don't include homology in the schema - leave it entirely to downstream interpretation

This makes matching identical variants difficult and requires defining a 'canonical' breakpoint location which is the opposite of the SPDI approach. I think A or B could be made to work with some more thought about edge case behaviour.

  - "(following an end-defined sequence terminal)" is unclear
  - "be consistent" -> "be identical" ? mixing hg19+hg38 can be "consistent"
  - Mention rules around omitting sequences?

  - Any shortcut for high-depth paths?
    - In practice, this only really impacts BFB
  - Is there any way to same-molecule phase variants without defining relative order?
    - How to express high CN variants? E.g. double minute 100 copies of a variant

2. CN

- No support for admixture CN (e.g. raw CN of a tumour sample).
  - Can we add support for type: float (https://github.com/ga4gh/vrs/issues/445)
 
- Do we want to support ASCN? Unclear how we can link allele-specific copy number SystemicVariation with the MolecularVariation small variants used to make the ASCN calls.

3. Genotype
- Also no support for raw floating point VAFs.

-

4. ReferenceLengthExpression

- Does ReferenceLengthExpression.sequence refer to the overall sequence or the repeatSubunitLength?

VCFv4.4 introduced the following fields:
```
##INFO=<ID=RUS,Number=.,Type=String,Description="Repeat unit sequence of the corresponding repeat sequence">
##INFO=<ID=RUL,Number=.,Type=Integer,Description="Repeat unit length of the corresponding repeat sequence">
##INFO=<ID=RUC,Number=.,Type=Float,Description="Repeat unit count of corresponding repeat sequence">
##INFO=<ID=RB,Number=.,Type=Integer,Description="Total number of bases in the corresponding repeat sequence">
##INFO=<ID=CIRUC,Number=.,Type=Float,Description="Confidence interval around RUC">
##INFO=<ID=CIRB,Number=.,Type=Integer,Description="Confidence interval around RB">
##INFO=<ID=RUB,Number=.,Type=Integer,Description="Number of bases in each individual repeat unit">
```

Which allows expressing most repeats but doesn't handle nested repeats (e.g. a STR in a VNTR where the STR length changes for each repeat of the VNTR).

5. DerivedSequenceExpression

Did you decide on where an exact match to a interval of reference sequence can be included in the model? I.e. VCF `<*>/<NON_REF>` reference blocks.

6. Adjacency

- How about we use `connectedSequence` instead of `sequenceTerminal`?

It's reasonably clear what is meant and the term isn't overloaded with alternative meanings like so many other terms are.

Not particular need on `linker` either but happy to let that go through to the wider audience for feedback.

7. Event

What a good venue for discussing this with a wider audience? It feels like in should be in VA but at the same time I feel like we'll get pushback if we put out a model that doesn't call anything a deletion.

**Comment by ahwagner** [comment]
1a. We will make change to Haplotype definition
1b. We will open up new issue on Adjacency bounds overlap
1c. Yes, "identical" not "consistent"
1d. @larrybabb to write VRS 2.0 philosophy, will address rules for shared data structures, and resolving IRIs (new issue)
1e. @d-cameron to illustrate nested variation for test case development
1f. going to punt on in-phase SNPs on rearranged chromosomes with incomplete structural information
2. @d-cameron to create issue, create examples, and raise as discussion
3. @larrybabb to investigate existing efforts for variant call data for developing related spec (e.g. clinical VCF)
4. @ahwagner to reaffirm the sequence attribute as full-length sequence representation
5. deprecated
6. revise to `adjoinedSequences`
7. This is part of the community model discussion–not in VRS, but important. Let's talk in VR about it, just not in the VRS product.
