### ISSUE TITLE
Rename `sequenceTerminals` to `adjoinedSequences` in the new Adjacency class in 2.0

### ISSUE THREAD

**Issue by larrybabb** [ga4gh/vrs#456]
During the 12/7/23 SV meeting @d-cameron and the group discussed the new `Adjacency` class and mentioned the need to rename the `sequenceTerminals` attribute to provide a clearer term for what was being represented in that attribute. The term `connection` was offered as a better alternative.

**Comment by ahwagner** [comment]
I think we discussed 'junction' for this, and that term would be my preference due to it 1) having intuitive semantics as part of an adjacency and 2) aligning with the VICC Fusions and HGVS terminologies.

**Comment by larrybabb** [comment]
@d-cameron I know on the last call you and I seem to settle on `connection` but @ahwagner is making the point that `junction` would be better. I think you were hesitant to go with `junction`. Can you weigh in on whether `junction` is acceptable or not? It would be nice to get this closed out asap.

**Comment by ahwagner** [comment]
I was wrong. I looked back at our notes, [we all agreed on](https://github.com/ga4gh/vrs/issues/449#issuecomment-1828943177) `adjoinedSequences`.

**Comment by larrybabb** [comment]
@ahwagner Since the `adjoinedSequences` attribute on `Adjacency` can be either 1 or 2 `sequences`, should we drop the plural form of the attribute name?  Or go with `adjoinment` ( or something that represents the notion of one or two end points on one or two sequences that are involved in the Adjacency?

**Comment by larrybabb** [comment]
@ahwagner new question : Does the `linker` property of the `Adjacency` ONLY work if there are 2 `adjoinedSequences`? Or can you have a `linker` when there is only 1 `adjoinedSequences`?

**Comment by d-cameron** [comment]
Linker works even when you only have one side. Vcf single breakends will
contain the (partial) sequence that is connected to the ref and the given
location. Typically this occurs when one side cannot be unambiguously
placed (e.g. SV into a centromere) or not placed at all (e.g. viral
integration against a host-only reference).
