### ISSUE TITLE
Implement Abundance and Molecular Copy classes

### ISSUE THREAD

**Issue by reece** [ga4gh/vrs#46]
The goal for this issue is to write a single document with CNV use cases and a proposed model. 

This issue subsumes all prior discussions regarding CNVs (#23, #37, #39, #41, #42, #45). Those issues are now locked. All model discussions should occur here.

**Comment by ahwagner** [comment]
We need to update the .rst for Abundance concepts. Currently has a placeholder in the `Parking Lot` section.
