### ISSUE TITLE
Create schema-level constraint for start/stop on SequenceLocation within Adjacencies

### ISSUE THREAD

**Issue by Mrinal-Thomas-Epic** [ga4gh/vrs#474]
Currently, the `SequenceLocation` within an `Adjacency` is expected to have either `start` or `stop` populated, but not both. The constraint that both should not be populated is not specified anywhere in the schema, which could lead to confusion (e.g., discussion #471).

**Comment by ahwagner** [comment]
@Mrinal-Thomas-Epic this is great, thanks. Would you be interested in drafting the schema change?

**Comment by Mrinal-Thomas-Epic** [comment]
I'll take a stab at draft the schema change. Before I write it out, do you or @d-cameron have any thoughts on whether it should just be implemented as just a constraint on the use of SequenceLocation within Adjacency, or whether we should make a different class for a point + direction on a sequence?

**Comment by ahwagner** [comment]
@Mrinal-Thomas-Epic I think a constraint definition makes the most sense for forward compatibility.
