### ISSUE TITLE
Revise Haplotype model and add DerivativeMolecule

### ISSUE THREAD

**Issue by ahwagner** [ga4gh/vrs#481]
### Discussed in https://github.com/ga4gh/vrs/discussions/461

<div type='discussions-op-text'>

<sup>Originally posted by @ahwagner in https://github.com/ga4gh/vrs/discussions/461#discussioncomment-8833511</sup>
A draft model of 4 proposed changes between VRS 1.x to 2.x to support structural variation:

1. The Haplotype class gets renamed to CisPhasedBlock to differentiate between this concept and the notions of ancestry and linkage typically associated with Haplotype (leading to some of the concerns stated in https://github.com/ga4gh/vrs/discussions/461#discussioncomment-8334579).
2. A new DerivativeMolecule class is developed that allows construction of novel contiguous molecules from multiple adjacencies and CisPhasedBlocks.
3. The previously-described Adjacency class is added that allows for the representation of two adjacent sequences and an optional intervening linker sequence expression.
4. A new Terminus class is added that allows for the specification of a single sequence location, representing the end of a sequence.

These changes address the concerns about ordered / unordered variant members by creating data classes specifically for each of cis-phased variant and derivative sequences.</div>

**Comment by ahwagner** [comment]
Additional changes, discussed at Connect:

- [x] Adjacency class specifies how to interpret ranges (instrument ambiguity vs. homology) (a7d7541)
- [x] DerivativeMolecule class has an attribute to specify if it represents a circular molecule (9223ae7)

**Comment by larrybabb** [comment]
@ahwagner I moved this to done because it looks like its done. please revert if I misunderstood.
