### ISSUE TITLE
2.0 implementation trial use review

### ISSUE THREAD

**Issue by ahwagner** [ga4gh/vrs#521]
Classes for review:
- [ ] SequenceLocation
- [ ] Allele
- [ ] CisPhasedBlock
- [ ] CopyNumberCount
- [ ] CopyNumberChange
- [ ] Adjacency
- [ ] DerivativeMolecule
- [ ] Terminus
- [ ] TraversalBlock
- [ ] ReferenceLengthExpression
- [ ] LengthExpression

Conventions for review:
- [ ] Allele Normalization
- [ ] Adjacency Normalization

**Comment by larrybabb** [comment]
Officially launched the Trial Use Review with the VRS working group on Aug.12. We will close the loop on this on Sep.9.

**Comment by ahwagner** [comment]
Adjusted start and target dates to match delayed publication of pre-release.

**Comment by larrybabb** [comment]
@ahwagner is this done?
