### ISSUE TITLE
Create class hierarchy diagram

### ISSUE THREAD

**Issue by ahwagner** [ga4gh/vrs#561]
From #533:
> Please add a figure showing the class hierarchy to illustrate inheritance. This would be especially helpful for an abstract class like Location, which is listed as a datatype for several attributes but is not included in the documentation so it is difficult to know which child classes are valid for a given attribute.

**Comment by larrybabb** [comment]
Here's the class diagram. 
![GKS Product Organization - VRS 2 0 Class Diagram](https://github.com/user-attachments/assets/6e8a2ca0-e09d-4e7c-9a43-a9dd2f3a6925)

**Comment by larrybabb** [comment]
@ahwagner  and others.... I'd love any feedback in terms of making the diagram easier to understand. I do think we may need different versions or representations of the class diagram, including more detailed versions focused on individual classes. But for now we are trying to get the basic view down to a single page to give users a sense of the scope and breadth and organization of VRS.

**Comment by ahwagner** [comment]
This looks good to me. FWIW, I think this is exactly the level of detail needed for this diagram, which covers a lot of ground.

**Comment by Mrinal-Thomas-Epic** [comment]
This is a great one page overview! I think the only thing that might be helpful to add is a "uses" type relationship (e.g., `Allele` uses `SequenceLocation` and `SequenceExpression`)

**Comment by rrfreimuth** [comment]
Thanks, @larrybabb ! I think this is great. The "inheritance view" is important and aids understanding.

A single diagram cannot show everything. I agree that another diagram that illustrates more of a structural domain perspective (detail within the classes and relevant relations/compositions) would also be helpful at some point.

**Comment by ahwagner** [comment]
@larrybabb one update to request: `Ga4ghIdentifiableObject` is in VRS, not `gks.core`. We should either move it up to core (I would prefer this), or revise this figure to match the spec. Otherwise I think this looks good.

**Comment by larrybabb** [comment]
![Image](https://github.com/user-attachments/assets/67c16088-d94a-4504-a614-9acd662b40a9)

**Comment by korikuzma** [comment]
@larrybabb how do you decide on when to include ABC? For example, `Variation` is included, but `MolecularVariation`, `SystemicVariation`, and `Location` are not.

**Comment by korikuzma** [comment]
@larrybabb `LiteralSequenceExpression` `vrs` is black, but should be blue

**Comment by korikuzma** [comment]
@larrybabb `CisPhaseBlock` --> `CisPhasedBlock`

**Comment by larrybabb** [comment]
> [@larrybabb](https://github.com/larrybabb) how do you decide on when to include ABC? For example, `Variation` is included, but `MolecularVariation`, `SystemicVariation`, and `Location` are not.

@korikuzma Alex and I decided that only Classes that are strictly organizational do not go in the class hierarchy diagram. Since `MolecularVariation` and `SystemicVariation` are more about grouping types of `Variation` we did not include them in the more technical inheritance class diagram.  Does that make sense? (please discuss with Alex as well)

**Comment by korikuzma** [comment]
> > [@larrybabb](https://github.com/larrybabb) how do you decide on when to include ABC? For example, `Variation` is included, but `MolecularVariation`, `SystemicVariation`, and `Location` are not.
> 
> @korikuzma Alex and I decided that only Classes that are strictly organizational do not go in the class hierarchy diagram. Since `MolecularVariation` and `SystemicVariation` are more about grouping types of `Variation` we did not include them in the more technical inheritance class diagram. Does that make sense? (please discuss with Alex as well)

@larrybabb that makes sense. But what about `Location`, it seems similar to `Variation`?

**Comment by korikuzma** [comment]
@larrybabb ^

**Comment by larrybabb** [comment]
#I don't think `Location` should be in our class hierarchy since there's no reason for it. 

So I'm keeping it hidden so when we remove it there's no harm done.
