### ISSUE TITLE
Create examples in docs pages

### ISSUE THREAD

**Issue by ahwagner** [ga4gh/vrs#562]
> Please include links to examples from within concept/model pages, so it is easier to see instance examples of each class

**Comment by larrybabb** [comment]
@ahwagner if you want to mock up one or two of these then I will follow the lead and pitch in. If not, please let me know if you need me to take the lead on this.  Also, let me know when this needs to be completed.

**Comment by korikuzma** [comment]
Will this just pull from our validation examples? https://github.com/ga4gh/vrs/blob/2.x/validation/models.yaml
