### ISSUE TITLE
Add digest and key info to RTD docs

### ISSUE THREAD

**Issue by ahwagner** [ga4gh/vrs#569]
Currently the `ga4gh` field info may be found in schema, but not in docs. Update the metaschema processor tooling to include this information when available.

**Comment by korikuzma** [comment]
PR in MSP is here: https://github.com/ga4gh/gks-metaschema/pull/29

**Comment by larrybabb** [comment]
@korikuzma fixed this with b16 of the MSP. I was able to apply it on Nov.07.2024 to the GKS stack and VRS 2.x specifically.
